name: "CI Builds"

on: [push, workflow_dispatch]

env:
  VEYON_VERSION: v4.9.0

jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - fedora.41
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/ci.linux.${{ matrix.dist }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: veyon/veyon
          ref: ${{ env.VEYON_VERSION }}
          path: veyon
          submodules: true

      - run: .ci/linux.${{ matrix.dist }}/script.sh $GITHUB_WORKSPACE/veyon /tmp
