name: "CI Builds"

on: [workflow_dispatch]

env:
  VEYON_VERSION: v4.9.0

jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - fedora.41
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/ci.linux.${{ matrix.dist }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          list_dir() {
            local dir="$1"  # Current directory
            local prefix="$2"  # Indentation prefix

            # List contents of the current directory
            for entry in "$dir"/*; do
              if [ -e "$entry" ]; then
                # Extract the basename of the entry
                local name=$(basename "$entry")
                echo "${prefix}${name}"

                # If entry is a directory, recursively call list_dir
                if [ -d "$entry" ]; then
                  list_dir "$entry" "${prefix}    "
                fi
              fi
            done
          }
          list_dir "." "  "

      # - uses: actions/checkout@v4
      #   with:
      #     repository: veyon/veyon
      #     ref: ${{ env.VEYON_VERSION }}
      #     path: veyon
      #     submodules: true

      # - run: ${{ github.workspace }}/.ci/linux.${{ matrix.dist }}/script.sh ${{ github.workspace }}/veyon /tmp
      #   working-directory: ${{ github.workspace }}/veyon
