name: "CI Container builds"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 10 * * 1

jobs:
  build-container:
    strategy:
      matrix:
        dist:
          - fedora.41
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/ci.linux.${{ matrix.dist }}
          tags: |
            type=raw,value=latest

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .ci/linux.${{ matrix.dist }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
